### ISSUE TITLE
Show request: V (2009)

### ISSUE THREAD

**Issue by michaelgoodier** [xdpirate/isitcutshort.com#36]
This show was cut short on a cliffhanger: https://en.wikipedia.org/wiki/V_(2009_TV_series)#Cancellation_response

https://m.imdb.com/title/tt1307824/

Also - have you thought about scraping these tables (and filtering to the ones that say cancelled?) 

https://en.wikipedia.org/wiki/2019_in_American_television#Shows_ending_in_2019

**Comment by xdpirate** [comment]
Hey! Yeah, that's a good idea. The only problem with scraping data like that is that we only get the cancellation status and not the cliffhanger status.... But since I introduced a flag for "no data on cliffhanger" the other day (for example on [Deadbeat](https://www.isitcutshort.com/?q=Deadbeat+%282014%29) I couldn't find conclusive data on whether it ended on a cliffhanger), I can still parse them into the DB and input cliffhanger data when I or someone else provide that data.

Thanks! I will add the show next time I work on adding data!
